## Path to dataset
dataset_path: '/home/niksta/Documents/datasets_2'
## Dataset to be used: default: kitti
dataset: 'SemanticKitti'
## KITTI sequences to use -> List[str]
kitti_sequences: ['05', '06']
# '00', '06'
## Choose descriptor -> str
descriptor: 'ot' # 'ot' or 'sc'
## Read descriptors from file or generate them -> bool
from_file: False
## Path to weights file if using learning-based descriptor (e.g. 'ot') -> str
weights_path: '/home/niksta/python_projects/opt-key/optkey_utils/descriptors/OverlapTransformer/config/weights/pretrained_overlap_transformer.pth.tar'
## Path to save results
save_path: /home/niksta/python_projects/opt-key/results

## Optimization parameters
## Alpha weight (rmt) -> float
alpha: 1.0
## Beta weight (ipt) -> float
beta: 1.0
## Min multiplier
min_mult: 0.1 # 0.0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0
## Max multiplier
max_mult: 3.0  # 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0
## Window size -> int
window_size: 10
